
name: first_workflow
on: workflow_dispatch
jobs:
   
   job1_greetings:
     runs-on: ubuntu-latest
     steps:
        - name: my first job first step
          run: echo "hello Mahesh"
       
        - name: my first job second step
          run: echo "how are you"
   job2_details:
      runs-on: ubuntu-latest
      needs: job1
      steps:
         -run: echo "I am from india"
